#window settings
WIDTH = 500
HEIGHT = 500
TITLE = "Flappy Bird DVA NOL"

#bird settings
SPAWN_X = WIDTH//2
SPAWN_Y = HEIGHT//2
SIZE = 20
MAXIMUM_JUMP = 50
CURIOSITY = 10
JUMP_PER_FRAME = MAXIMUM_JUMP // CURIOSITY
FALL_SPEED = 2
BORDER = 2
AIR_BLOCK = 2

#walls settings 
MAX_WALLS = 8
SPACE_IN_BEETWEN = 150
DISTANCE = 200
LENGHT = 50
WALL_X = HEIGHT + DISTANCE
SPEED = 2

#bg settings
BG_ENDPOINT = 500
BG_SPEED = SPEED
BG_WIDTH = 500
BG_HEIGHT = 500

#color settings
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)