
print("Timuruch bbs oficial server")
print("Here will be my new news abou my git or my future or not future projects")
print("")
print("04.09.2021 20:02")
print("Hello i update my bbs server and today we have a new program")
print("Which name is 'News surfer' this program will show this message")
print("Much easier than another old")
print("")
print("Maybe i will made another project what will called 'CMDER' it will use")
print("for easy access to my apps and easier compilier for python")
print("Now i work for it and it is on Beta 5.0 i think i will post it at release 1.0")
print("")
print("05.09.2021 12:39")
print("Good moning and today i will anonse a news surfer Beta 1.1")
print("It will fix some bugs")
print("")
print("I will make a special server for 'CMDER' and code will be 2345")
print("There i will post news about 'CMDER' and updates or programs for it")
print("")
print("I work with 'Simple archipaint' it will be a like a microsoft paint")
print("But i will remake for all my OS programs because i will need a")
print("Some grapfics for it and 'CMDER' work ony with .ghl files")
print("Microsoft paint can't ddo this but it's will to hard to")
print("Compilate it from .ghl to .jpg or another")
print("")
print("27.10.2021 14:08")
print("Hello, i am working on my new project named LANI. It will be a game engine but")
print("Not, a simple engine, it will be like doom but easily to edit.")
print("I'm working on updates to TNS(Timuruch News System) now this program will named TNS")
print("not bbs")
print("Thats all.")
